/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lgfrnhhlutwahptczwko"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZnJuaGhsdXR3YWhwdGN6d2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxODkyMzMsImV4cCI6MjA4MTc2NTIzM30.2djZIorsw9yb1cZ1tYH0El_ZOERYnXWcpgCr-6231-Y"